"""
Train MLP classifiers for all τ-threshold ablation variants.

This script trains 6 separate models (one for each τ threshold) using the
stratified train/test splits generated by create_unambiguous_test_set.py.

All models are trained with identical hyperparameters to ensure fair comparison:
- Feature set: "important" (10 features)
- Hidden dim: 64
- Batch size: 32
- Learning rate: 1e-3
- Epochs: 100 (with early stopping)

Usage:
    python scripts/sufficiency_classifier/train_ablation_models.py \
        --splits_dir data/ablation/splits \
        --output_dir results/ablation/models \
        --features important

    # Or run in background and log all output
    nohup python scripts/sufficiency_classifier/train_ablation_models.py > results/ablation/training.log 2>&1 &
"""

import argparse
import json
import logging
import subprocess
import time
from pathlib import Path
from typing import List, Dict, Any

try:
    from tau_config import TAU_THRESHOLDS
except ImportError:
    import sys
    sys.path.append(str(Path(__file__).parent))
    from tau_config import TAU_THRESHOLDS

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')


def train_model(
    train_data_path: str,
    output_dir: str,
    tau: float,
    features: str = "important",
    epochs: int = 100,
    batch_size: int = 32,
    lr: float = 1e-3,
    hidden_dim: int = 64
) -> Dict[str, Any]:
    """
    Train a single model for a given τ threshold.

    Returns:
        Training metrics and metadata
    """
    tau_str = f"{tau:.2f}"
    model_dir = Path(output_dir) / f"tau_{tau_str}"
    model_dir.mkdir(parents=True, exist_ok=True)

    logging.info(f"\n{'='*80}")
    logging.info(f"Training model for τ={tau_str}")
    logging.info(f"{'='*80}")
    logging.info(f"Train data: {train_data_path}")
    logging.info(f"Output dir: {model_dir}")

    # Build command
    cmd = [
        "uv", "run", "python",
        "scripts/sufficiency_classifier/train_mlp_classifier.py",
        "--data_path", train_data_path,
        "--output_dir", str(model_dir),
        "--features", features,
        "--epochs", str(epochs),
        "--batch_size", str(batch_size),
        "--lr", str(lr),
        "--hidden_dim", str(hidden_dim)
    ]

    logging.info(f"Command: {' '.join(cmd)}")

    # Run training
    start_time = time.time()
    result = subprocess.run(cmd, capture_output=True, text=True)
    elapsed_time = time.time() - start_time

    if result.returncode != 0:
        logging.error(f"Training failed for τ={tau_str}")
        logging.error(result.stderr)
        return {
            "tau": tau,
            "status": "failed",
            "error": result.stderr[:500],
            "elapsed_time": elapsed_time
        }

    # Parse metrics from training output
    metrics = parse_training_metrics(result.stderr)
    metrics["tau"] = tau
    metrics["status"] = "success"
    metrics["elapsed_time"] = elapsed_time
    metrics["model_dir"] = str(model_dir)

    logging.info(f"✓ Training completed in {elapsed_time:.1f}s")
    logging.info(f"  Test Accuracy:  {metrics.get('test_accuracy', '?'):.4f}")
    logging.info(f"  Test F1:        {metrics.get('test_f1', '?'):.4f}")
    logging.info(f"  Test Precision: {metrics.get('test_precision', '?'):.4f}")
    logging.info(f"  Test Recall:    {metrics.get('test_recall', '?'):.4f}")

    return metrics


def parse_training_metrics(output: str) -> Dict[str, float]:
    """Parse test metrics from training script output."""
    metrics = {}

    for line in output.split('\n'):
        line = line.strip()

        if "Accuracy:" in line:
            try:
                metrics['test_accuracy'] = float(line.split()[-1])
            except (ValueError, IndexError):
                pass
        elif "Precision:" in line:
            try:
                metrics['test_precision'] = float(line.split()[-1])
            except (ValueError, IndexError):
                pass
        elif "Recall:" in line:
            try:
                metrics['test_recall'] = float(line.split()[-1])
            except (ValueError, IndexError):
                pass
        elif "F1 Score:" in line:
            try:
                metrics['test_f1'] = float(line.split()[-1])
            except (ValueError, IndexError):
                pass

    return metrics


def generate_summary_report(all_metrics: List[Dict[str, Any]], output_dir: Path):
    """Generate summary report of all training runs."""

    # Save JSON report
    report_json = output_dir / "training_summary.json"
    with open(report_json, 'w') as f:
        json.dump(all_metrics, f, indent=2)
    logging.info(f"\n✓ Saved training summary to {report_json}")

    # Save CSV report
    report_csv = output_dir / "training_summary.csv"
    with open(report_csv, 'w') as f:
        f.write("tau,status,test_accuracy,test_f1,test_precision,test_recall,elapsed_time\n")
        for m in all_metrics:
            f.write(
                f"{m.get('tau', 0):.2f},"
                f"{m.get('status', 'unknown')},"
                f"{m.get('test_accuracy', 0):.4f},"
                f"{m.get('test_f1', 0):.4f},"
                f"{m.get('test_precision', 0):.4f},"
                f"{m.get('test_recall', 0):.4f},"
                f"{m.get('elapsed_time', 0):.1f}\n"
            )
    logging.info(f"✓ Saved training summary to {report_csv}")

    # Print summary table
    logging.info("\n" + "="*100)
    logging.info("ABLATION TRAINING SUMMARY")
    logging.info("="*100)
    logging.info(f"{'τ':>6} | {'Status':>8} | {'Accuracy':>9} | {'F1':>7} | {'Precision':>10} | {'Recall':>7} | {'Time (s)':>9}")
    logging.info("-"*100)
    for m in all_metrics:
        logging.info(
            f"{m.get('tau', 0):>6.2f} | "
            f"{m.get('status', 'unknown'):>8} | "
            f"{m.get('test_accuracy', 0):>9.4f} | "
            f"{m.get('test_f1', 0):>7.4f} | "
            f"{m.get('test_precision', 0):>10.4f} | "
            f"{m.get('test_recall', 0):>7.4f} | "
            f"{m.get('elapsed_time', 0):>9.1f}"
        )
    logging.info("="*100)


def main():
    parser = argparse.ArgumentParser(description="Train ablation models for all τ thresholds")
    parser.add_argument("--splits_dir", type=str,
                       default="data/ablation/splits",
                       help="Directory containing train/test splits")
    parser.add_argument("--output_dir", type=str,
                       default="results/ablation/models",
                       help="Output directory for trained models")
    parser.add_argument("--thresholds", type=float, nargs="+",
                       default=None,
                       help="List of τ thresholds to train (defaults to tau_config.TAU_THRESHOLDS)")
    parser.add_argument("--features", type=str, default="important",
                       help="Feature preset to use")
    parser.add_argument("--epochs", type=int, default=100,
                       help="Number of training epochs")
    parser.add_argument("--batch_size", type=int, default=32,
                       help="Batch size")
    parser.add_argument("--lr", type=float, default=1e-3,
                       help="Learning rate")
    parser.add_argument("--hidden_dim", type=int, default=64,
                       help="Hidden layer dimension")

    args = parser.parse_args()

    if args.thresholds is None:
        args.thresholds = TAU_THRESHOLDS

    splits_dir = Path(args.splits_dir)
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    logging.info(f"Training {len(args.thresholds)} models for τ-threshold ablation study")
    logging.info(f"Splits directory: {splits_dir}")
    logging.info(f"Output directory: {output_dir}")
    logging.info(f"Feature preset: {args.features}")
    logging.info(f"Hyperparameters: epochs={args.epochs}, batch_size={args.batch_size}, "
                f"lr={args.lr}, hidden_dim={args.hidden_dim}")

    # Train all models
    all_metrics = []
    for tau in args.thresholds:
        tau_str = f"{tau:.2f}"
        train_data_path = splits_dir / f"tau_{tau_str}_train.json"

        if not train_data_path.exists():
            logging.error(f"Training data not found: {train_data_path}")
            logging.info("Please run create_unambiguous_test_set.py first")
            continue

        metrics = train_model(
            train_data_path=str(train_data_path),
            output_dir=str(output_dir),
            tau=tau,
            features=args.features,
            epochs=args.epochs,
            batch_size=args.batch_size,
            lr=args.lr,
            hidden_dim=args.hidden_dim
        )
        all_metrics.append(metrics)

    # Generate summary report
    if all_metrics:
        generate_summary_report(all_metrics, output_dir)

    logging.info("\n✓ All training jobs completed!")
    logging.info(f"Models saved to: {output_dir}")

    # Check for failures
    failed = [m for m in all_metrics if m.get('status') != 'success']
    if failed:
        logging.warning(f"\n⚠ {len(failed)} training job(s) failed:")
        for m in failed:
            logging.warning(f"  τ={m.get('tau')}: {m.get('error', 'Unknown error')[:100]}")


if __name__ == "__main__":
    main()
